runtime: nodejs18
service: api

instance_class: F2

env_variables:
  MYSQL_HOST: '34.128.113.6'
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: ''
  MYSQL_DATABASE: 'praktikum'

handlers:
  - url: /.*
    script: auto
